language: python
python:
  - "2.7"

install:
  - ./setup.py install
  - pip install -r requirements.txt
  - pip install codacy-coverage codecov nosexcover

script: nosetests --verbose --with-xcover --cover-package=telegrambot
